# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lipapp', '0002_auto_20160518_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='rating',
            field=models.CharField(choices=[(1, 'G'), (2, 'PG'), (3, 'PG-13'), (4, '14A'), (5, 'R'), (6, 'NR')], default=datetime.datetime(2016, 5, 25, 14, 0, 18, 78485, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 5, 25)),
        ),
    ]
