# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipapp', '0007_auto_20160701_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 7, 3)),
        ),
    ]
