# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 16:26
from __future__ import unicode_literals

from __future__ import unicode_literals

from django.db import migrations, models


def load_lipapp_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "lipapp")


class Migration(migrations.Migration):

    dependencies = [
        ('lipapp', '0008_auto_20160703_0159'),
    ]

    operations = [
        migrations.RunPython(load_lipapp_from_fixture)
    ]
